### ISSUE TITLE
Not able to Find Authorisation

### ISSUE THREAD

**Issue by VinayakPastey** [CasCard/AutoCDSL#5]
I am getting the following error , when I try to run the lambda function
```
{
  "errorMessage": "Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='Authorisation']\"}\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.14.255-328-268.540.amzn2.x86_64 x86_64)\n",
  "errorType": "NoSuchElementException",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 156, in lambda_handler\n    driver.find_element_by_xpath(\"//a[text()='Authorisation']\").click()\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"
  ]
}
```

As a developer myself, I try to debug the issue. I found that, the login is not working as expected. 
When I try to print the current_url after login, or after redirecting to holdings page, the url is 
`https://kite.zerodha.com/?next=%2Fholdings` which is the login page.

That is why we the above error (authorisation button not found), as its not even logged properly. 

@CasCard Let me know if you are working on it. Thanks :)

**Comment by CasCard** [comment]
Hi Thank you for reporting the issue, I have made a small change to the lambda_function.py file, can you replace the current code content with the new one, now it should be working. Thanks

**Comment by VinayakPastey** [comment]
Thanks works now :+1: 

Hi, another suggestion for improvement would be notifications, about the success and failures. I have implemented it on my own with gmail itself, but would love to have a more concrete notification design.
